name: devsecops pipeline

on: [push, pull_request]

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build the app with Gradle
        run: ./gradlew build -x test

      - name: Install Snyk CLI
        run: |
          curl -sL https://snyk.io/install | bash
          echo "$HOME/.snyk" >> $GITHUB_PATH

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Open Source Scan (SCA)
        run: snyk test --all-projects --severity-threshold=medium

      - name: Snyk Code Scan (SAST)
        run: snyk code test
