name: devsecops pipeline

on: [push, pull_request]

jobs:
  code-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build the app with Maven
        run: mvn clean install -DskipTests -Dprocess-exec.skip=true -pl '!webgoat-container'

      - name: Run Semgrep scan 
        uses: returntocorp/semgrep-action@v1
        with:
          config: "auto"
