name: devsecops pipeline # A name for workflow

on: [push, pull_request]           # when to run the workflows
                                    # on push events 
                                     # specify branches
                                    # Run on pushes to the 'main' branch 
jobs:
  code-scan:
   runs-on: ubuntu-latest 

   steps:
   - name: checkout code 
     uses: actions/checkout@v3

   - name: Set up java
     uses: actions/setup-java@v3 
     with:
      java-version: '17'
      distribution: 'temurin'

   - name: Build the app with maven
     run: mvn clean install -DskipTests 

   - name: Run Semgrep scan 
     uses: returntocorp/semgrep-action@v1 
     with:
      config: "auto"



